// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TdlibBridgePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Mirrors the subset of TdApi.AuthorizationState this module surfaces to Dart
 * (see app.oxplayer.tdlibbridge.auth.TdlibAuthState on the Kotlin side).
 */
enum class OxTdlibAuthStateKind(val raw: Int) {
  UNINITIALIZED(0),
  WAITING_FOR_PHONE_NUMBER(1),
  WAITING_FOR_CODE(2),
  WAITING_FOR_PASSWORD(3),
  WAITING_FOR_QR_CONFIRMATION(4),
  READY(5),
  LOGGING_OUT(6),
  CLOSED(7),
  FAILED(8);

  companion object {
    fun ofRaw(raw: Int): OxTdlibAuthStateKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OxTdlibAuthState (
  val kind: OxTdlibAuthStateKind,
  val qrLoginUrl: String? = null,
  val passwordHint: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OxTdlibAuthState {
      val kind = pigeonVar_list[0] as OxTdlibAuthStateKind
      val qrLoginUrl = pigeonVar_list[1] as String?
      val passwordHint = pigeonVar_list[2] as String?
      val errorMessage = pigeonVar_list[3] as String?
      return OxTdlibAuthState(kind, qrLoginUrl, passwordHint, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      qrLoginUrl,
      passwordHint,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OxTdlibAuthState) {
      return false
    }
    if (this === other) {
      return true
    }
    return TdlibBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * One playback session's Telegram-backed video source, resolved from the
 * PlaybackInfo structured fields (TelegramChannelUsername / TelegramMessageId).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OxTdlibPlaybackSource (
  val channelUsername: String,
  val messageId: Long,
  /**
   * True when the target player is mpv/mdk (no DataSource-style hook for a custom scheme) —
   * returns a http://127.0.0.1:{port}/{fileId} url served by TdlibHttpBridgeServer instead of
   * tdlib-file://{fileId}. False (default) keeps the existing ExoPlayer DataSource path.
   */
  val preferHttpBridge: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OxTdlibPlaybackSource {
      val channelUsername = pigeonVar_list[0] as String
      val messageId = pigeonVar_list[1] as Long
      val preferHttpBridge = pigeonVar_list[2] as Boolean
      return OxTdlibPlaybackSource(channelUsername, messageId, preferHttpBridge)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      channelUsername,
      messageId,
      preferHttpBridge,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OxTdlibPlaybackSource) {
      return false
    }
    if (this === other) {
      return true
    }
    return TdlibBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class TdlibBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OxTdlibAuthStateKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OxTdlibAuthState.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OxTdlibPlaybackSource.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OxTdlibAuthStateKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is OxTdlibAuthState -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is OxTdlibPlaybackSource -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OxTdlibBridgeApi {
  /**
   * Must be called once before any other method (idempotent) — starts the underlying
   * TDLib client with [apiId]/[apiHash] from OxplayerEnv (this module's own user-session
   * credentials, distinct from the bot-based OX login's credentials).
   */
  fun configure(apiId: Long, apiHash: String, callback: (Result<Unit>) -> Unit)
  /**
   * Current auth state; also pushed via OxTdlibBridgeEvents.onAuthStateChanged.
   * Synchronous — this just reads cached state, no TDLib round-trip.
   */
  fun currentAuthState(): OxTdlibAuthState
  /** Phone/tablet flow, step 1. Async: waits on the real TdApi round-trip. */
  fun submitPhoneNumber(phoneNumber: String, callback: (Result<Unit>) -> Unit)
  /** Phone/tablet flow, step 2. */
  fun submitCode(code: String, callback: (Result<Unit>) -> Unit)
  /** Phone/tablet flow, step 3 — only valid when state is waitingForPassword. */
  fun submitTwoFactorPassword(password: String, callback: (Result<Unit>) -> Unit)
  /**
   * Android TV flow: request a QR login token; UI renders the URL pushed via
   * onAuthStateChanged(waitingForQrConfirmation) as a QR code.
   */
  fun requestQrLogin(callback: (Result<Unit>) -> Unit)
  /** Server-side session invalidation + local TDLib session wipe. */
  fun logOut(callback: (Result<Unit>) -> Unit)
  /**
   * Resolves [source] and starts downloading via TDLib, returning either a
   * tdlib-file://{fileId} uri (ExoPlayer DataSource path) or, when
   * source.preferHttpBridge is true, a http://127.0.0.1:{port}/{fileId} uri served by
   * TdlibHttpBridgeServer (mpv/mdk path — see that class for why).
   * Throws if no MTProto/TDLib session is logged in yet — callers should
   * check currentAuthState() first and prompt login if not ready.
   */
  fun startPlaybackSession(source: OxTdlibPlaybackSource, callback: (Result<String>) -> Unit)
  /**
   * Stops the active playback session's download and closes the TDLib client (does not log
   * out — the on-disk session persists, next play just reconnects). Callers on every backend
   * (ExoPlayer's own hook is native-side via VideoPlayerImplementation.clearSession; mpv/mdk
   * have no equivalent Activity-scoped teardown, so their wrapper must call this explicitly
   * when a Telegram-sourced item finishes) — see TdlibBridgeObject.onTelegramPlaybackEnded.
   */
  fun stopPlaybackSession(sessionUri: String, callback: (Result<Unit>) -> Unit)
  /**
   * Fetches a Telegram-signed Mini App `initData` payload for [botUsername] via TDLib's
   * GetWebAppLinkUrl/GetWebAppUrl/GetMainWebApp — requires a Ready auth state (real Telegram
   * login already completed) and a Mini App configured on that bot via @BotFather. Exchange the
   * result with the backend's POST /auth/telegram to obtain OX session tokens; see
   * OxplayerTelegramAuthClient. [webAppShortName]/[hostedHttpsUrl] may be null/empty if unset —
   * at least one working WebApp path must be configured on the bot for this to succeed.
   */
  fun fetchWebAppInitData(botUsername: String, webAppShortName: String?, hostedHttpsUrl: String?, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by OxTdlibBridgeApi. */
    val codec: MessageCodec<Any?> by lazy {
      TdlibBridgePigeonCodec()
    }
    /** Sets up an instance of `OxTdlibBridgeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OxTdlibBridgeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiIdArg = args[0] as Long
            val apiHashArg = args[1] as String
            api.configure(apiIdArg, apiHashArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.currentAuthState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.currentAuthState())
            } catch (exception: Throwable) {
              TdlibBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.submitPhoneNumber$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val phoneNumberArg = args[0] as String
            api.submitPhoneNumber(phoneNumberArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.submitCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeArg = args[0] as String
            api.submitCode(codeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.submitTwoFactorPassword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val passwordArg = args[0] as String
            api.submitTwoFactorPassword(passwordArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.requestQrLogin$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestQrLogin{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.logOut$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logOut{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.startPlaybackSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as OxTdlibPlaybackSource
            api.startPlaybackSession(sourceArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TdlibBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.stopPlaybackSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionUriArg = args[0] as String
            api.stopPlaybackSession(sessionUriArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.fetchWebAppInitData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val botUsernameArg = args[0] as String
            val webAppShortNameArg = args[1] as String?
            val hostedHttpsUrlArg = args[2] as String?
            api.fetchWebAppInitData(botUsernameArg, webAppShortNameArg, hostedHttpsUrlArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TdlibBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class OxTdlibBridgeEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by OxTdlibBridgeEvents. */
    val codec: MessageCodec<Any?> by lazy {
      TdlibBridgePigeonCodec()
    }
  }
  fun onAuthStateChanged(stateArg: OxTdlibAuthState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeEvents.onAuthStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TdlibBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
