// Generated by scripts/sync-firebase-client-config.mjs — do not edit manually.
// Source: Infisical CONSOLE_FIREBASE (Firebase Admin SDK) + Firebase Management API.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:package_info_plus/package_info_plus.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions? _resolvedAndroid;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        final cached = _resolvedAndroid;
        if (cached != null) return cached;
        throw UnsupportedError(
          'Android FirebaseOptions not resolved yet — call DefaultFirebaseOptions.ensureAndroidResolved() before Firebase.initializeApp.',
        );
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform.',
        );
    }
  }

  /// Picks [android] vs [androidDev] from installed package name (Play flavors).
  static Future<FirebaseOptions> ensureAndroidResolved() async {
    if (_resolvedAndroid != null) return _resolvedAndroid!;
    final packageName = (await PackageInfo.fromPlatform()).packageName;
    _resolvedAndroid = packageName == 'app.oxplayer.dev' ? androidDev : android;
    return _resolvedAndroid!;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YxfcRDxwXa0hMRzBhaGzqNtZ1GdtAEI',
    appId: '1:637937620157:android:f31d26e7666f120ecf53d4',
    messagingSenderId: '637937620157',
    projectId: 'oxplayer-f5353',
    storageBucket: 'oxplayer-f5353.firebasestorage.app',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyD_YxfcRDxwXa0hMRzBhaGzqNtZ1GdtAEI',
    appId: '1:637937620157:android:3005e8a957fd5310cf53d4',
    messagingSenderId: '637937620157',
    projectId: 'oxplayer-f5353',
    storageBucket: 'oxplayer-f5353.firebasestorage.app',
  );
}
