/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package oxtelegram/cshared */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 8 "main.go"

#include <stdint.h>
#include <stdlib.h>

typedef void (*ox_auth_sink)(const char* kind, const char* qr_login_url, const char* password_hint, const char* error_message);

static void ox_auth_sink_invoke(ox_auth_sink fn, const char* a, const char* b, const char* c, const char* d) {
	if (fn) fn(a, b, c, d);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) char* ox_last_error(void);
extern __declspec(dllexport) void ox_free(char* p);
extern __declspec(dllexport) int ox_configure(int apiID, char* apiHash, char* sessionPath, char* cachePath, ox_auth_sink sink);
extern __declspec(dllexport) char* ox_current_auth_kind(void);
extern __declspec(dllexport) char* ox_current_auth_qr(void);
extern __declspec(dllexport) char* ox_current_auth_hint(void);
extern __declspec(dllexport) char* ox_current_auth_error(void);
extern __declspec(dllexport) int ox_submit_phone(char* phone);
extern __declspec(dllexport) int ox_submit_code(char* code);
extern __declspec(dllexport) int ox_submit_password(char* password);
extern __declspec(dllexport) int ox_request_qr(void);
extern __declspec(dllexport) int ox_logout(void);
extern __declspec(dllexport) char* ox_start_playback(char* channel, int64_t messageID);
extern __declspec(dllexport) int ox_stop_playback(char* sessionURI);
extern __declspec(dllexport) char* ox_fetch_webapp_init_data(char* bot, char* shortName, char* hostedURL, char* platform);

#ifdef __cplusplus
}
#endif
